### ISSUE TITLE
Failed to compile msc_external_flash, error "Error compiling for board ESP32S2 Native USB"

### ISSUE THREAD

**Issue by mihkel615** [adafruit/Adafruit_TinyUSB_Arduino#133]
### Operating System

Windows 10

### IDE version

1.8.16 (latest at the moment)

### Board

ESP32S2 Native USB, ESP32S2 Dev Module

### BSP version

2.0

### TinyUSB Library version

1.5.0 

### Sketch

Adafruit_TinyUSB_Arduino/examples/MassStorage/msc_external_flash/msc_external_flash.ino

### What happened ?

All my efforts on trying to compile it keeps failing. The compiler reaches the "Linking everything together" part and shortly after that fails with error message "Error compiling for board ESP32S2 Native USB".

### How to reproduce ?

Compile the example with the board selected and you should have it.

**Comment by hathach** [comment]
closed since it is fixed

**Comment by mihkel615** [comment]
Still having problems. Not sure, perhaps I'm missing something. I did manage to update the library to 1.6.0 but not compiling at all, does not matter if the board version is 2.0.0 or 2.0.1-rc1.

**Comment by hathach** [comment]
1. please **attach your compile log as txt** for analysis
2. try to build with one of adafruit board such as metro esp32s2. It could be one of the menu option that cause the compile issue. Make sure you compare menu option with Adafruit one.

**Comment by mihkel615** [comment]
When compiling with Metro selected, it will succeed only if "USB Firmware MSC On Boot" is disabled. I will attach the compiler log of this enabled.
[New Text Document.txt](https://github.com/adafruit/Adafruit_TinyUSB_Arduino/files/7486185/New.Text.Document.txt)

Thanks

**Comment by hathach** [comment]
"USB Firmware MSC On Boot" must be disabled (for now). Otherwise both built-in stack from esp and this library will have conflict over the msc driver control. There may or may not be a chance to have them both exists. But that requires more effort which I don't have a plan/time to look at now.

**Comment by mihkel615** [comment]
Ok, but after uploading nothing showed up on Files Explorer, even a port did not appear in Arduino IDE. But this might be due to the fact that I don't have a Metro, I have an ESP32S2 Wroom.

**Comment by hathach** [comment]
you should try with the msc_ramdisk first, it reduces the dependency on the hardware. You can select the esp32s2 dev board, make sure you follow the default usb-related option as metro such as cdc enabled, msc/dfu off etc ...

**Comment by mihkel615** [comment]
(Some) Success, the CDC enabled, MSC and DFU disabled was the magic formula, I managed to compile and upload the msc_external_flash example for ESP32S2 DEV board! But still, nothing appears on Files Explorer or even a port on Arduino IDE. With the same settings but using msc_ramdisk example, all works (except that ramdisk is quite useless in practice).

**Comment by hathach** [comment]
I am pretty sure it works with Adafruit boards last time I tested. In fact, lots of adafruit libraries used it to access the qflash storage. The difference can be the partition table, adafruit boards has different partition table for tinyuf2 (bootloader). You could try to look closer at the Adafuit_SPIFlash repo for code that access the qflash.

In any cases, this is not an issue of this library, saola board is generic and can be configured to match Adafruit Metro. Make sure you follow that closely.
